export const initialArizalar = [
  {
    firstName: "Akobir Sayfiyev",
    mealName: "Osh",
    price: "20 000",
    amount: "3",
    overall: "overall price",
    phone: "90 123 40 41",
    comment: "Lorem ipsum",
  },
  {
    firstName: "Lorem Ipsumov",
    mealName: "Osh",
    price: "20 000",
    amount: "5",
    overall: "overall price",
    phone: "90 123 40 41",
    comment: "Lorem ipsum",
  },
  {
    firstName: "Ter Stegen",
    mealName: "Manti",
    price: "5 000",
    amount: "10",
    overall: "overall price",
    phone: "90 123 40 41",
    comment: "Lorem ipsum",
  },
  {
    firstName: "Lorem Ipsumov",
    mealName: "Big Lavash",
    price: "24 000",
    amount: "3",
    overall: "overall price",
    phone: "90 123 40 41",
    comment: "Lorem ipsum",
  },
];
